### PR TITLE
Vfs class loaders

### PR DESCRIPTION
**Pull request by dlmarion**
Changes tested locally using the process in TESTING.md.

### CODE REVIEW

**Comment by dlmarion** [comment]
This might not compile until https://github.com/apache/accumulo/pull/1715 is merged.

**Comment by dlmarion** [comment]
apache/accumulo#1715 is merged. The checks are still not passing.

**Comment by ctubbsii** [comment]
> [apache/accumulo#1715](https://github.com/apache/accumulo/pull/1715) is merged. The checks are still not passing.

We'll have to wait until after ASF Jenkins publishes new SNAPSHOT builds.

**Comment by dlmarion** [comment]
What's the frequency of that?

**Comment by ctubbsii** [comment]
> What's the frequency of that?

I think daily. We can manually trigger it, but I don't think that it's necessary.

**Comment by dlmarion** [comment]
Agreed. I'll check it tomorrow. Thanks.

**Pull request merged**
